#線上數據庫環境
#mysql7.0
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    #druid連接池配置
    druid:
      #主庫數據源
      master:
        url: jdbc:mysql://172.17.0.2:3306/springbootv2?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
        username: root
        password: uqgCJEFHrm8CNghoT6+Ik6uaCiV8M+aG
      #備數據源 #關閉
      slave:
        enabled: false
        url: jdbc:mysql://172.17.0.2:3306/springbootv3?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
        username: root
        password: root
        #配置初始化連接數大小
      initial-size: 10
      # 最大連接數
      max-active: 50
      #最小連接數
      min-idle: 10
      #獲取連接等待超時時間
      max-wait: 5000
      pool-prepared-statements: true #是否緩存preparedStatement，也就是PSCache。PSCache對支持遊標的數據庫性能提升巨大，比如說oracle。在mysql下建議關閉。
      max-pool-prepared-statement-per-connection-size: 20
      validation-query: SELECT 1 FROM DUAL
      validation-query-timeout: 20000
      test-on-borrow: false #申請連接時執行validationQuery檢測連接是否有效，做了這個配置會降低性能。
      test-on-return: false #歸還連接時執行validationQuery檢測連接是否有效，做了這個配置會降低性能。
      test-while-idle: true #建議配置爲true，不影響性能，並且保證安全性。申請連接的時候檢測，如果空閒時間大於timeBetweenEvictionRunsMillis，執行validationQuery檢測連接是否有效。
      time-between-eviction-runs-millis: 60000 #配置間隔多久才進行一次檢測，檢測需要關閉的空閒連接，單位是毫秒
      min-evictable-idle-time-millis: 300000  #一個連接在池中最小生存的時間，單位是毫秒
      #StatViewServlet配置。（因爲暴露的監控信息比較敏感，支持密碼加密和訪問ip限定）
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        #可以增加訪問賬號密碼【去掉註釋就可以】
        #login-username: admin
        #login-password: admin
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
  redis:
    ssl: false
    database: 0
    host: 172.17.0.2
    port: 6379
    password:
    timeout: 1000
    lettuce:
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 10
        min-idle: 0
#mysql 8.0

#spring:
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    driverClassName: com.mysql.cj.jdbc.Driver
#    #druid連接池配置
#    druid:
#     # 主庫數據源
#     master:
#        url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT&autoReconnect=true&useSSL=false
#        username: root
#        password: root
#        #樹熊數據源
#     slave:
#        enabled : false
#        url: jdbc:mysql://localhost:3306/test2?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT&autoReconnect=true&useSSL=false
#        username: root
#        password: root
#        #配置初始化連接數大小
#     initial-size: 10
#     # 最大連接數
#     max-active: 50
#     #最小連接數
#     min-idle: 10
#     #獲取連接等待超時時間
#     max-wait: 5000
#     pool-prepared-statements: true #是否緩存preparedStatement，也就是PSCache。PSCache對支持遊標的數據庫性能提升巨大，比如說oracle。在mysql下建議關閉。
#     max-pool-prepared-statement-per-connection-size: 20
#     validation-query: SELECT 1 FROM DUAL
#     validation-query-timeout: 20000
#     test-on-borrow: false #申請連接時執行validationQuery檢測連接是否有效，做了這個配置會降低性能。
#     test-on-return: false #歸還連接時執行validationQuery檢測連接是否有效，做了這個配置會降低性能。
#     test-while-idle: true #建議配置爲true，不影響性能，並且保證安全性。申請連接的時候檢測，如果空閒時間大於timeBetweenEvictionRunsMillis，執行validationQuery檢測連接是否有效。
#     time-between-eviction-runs-millis: 60000 #配置間隔多久才進行一次檢測，檢測需要關閉的空閒連接，單位是毫秒
#     min-evictable-idle-time-millis: 300000  #一個連接在池中最小生存的時間，單位是毫秒
#     #StatViewServlet配置。（因爲暴露的監控信息比較敏感，支持密碼加密和訪問ip限定）
#     stat-view-servlet:
#      enabled: true
#      url-pattern: /druid/*
#      #可以增加訪問賬號密碼【去掉註釋就可以】
#      #login-username: admin
#      #login-password: admin
#     filter:
#      stat:
#        log-slow-sql: true
#        slow-sql-millis: 1000
#        merge-sql: true
#      wall:
#        config:
#          multi-statement-allow: true